services:
  app:
    build: .
    ports:
      - "3000:3000"
    links:
      - redis-server
      - monguito
    restart: always
  redis-server:
    image: redis
    ports:
      - "6379:6379"
  monguito:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=nico
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: